// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: nup_eye

#include "../ui.h"

lv_obj_t *uic_eye3;
lv_obj_t *uic_eye2;
lv_obj_t *uic_eye1;
lv_obj_t *uic_eye0;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_eye0 = NULL;lv_obj_t *ui_eye1 = NULL;lv_obj_t *ui_eye2 = NULL;lv_obj_t *ui_eye3 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_eye0 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_eye0, &ui_img_eye0_eye0_0_png);
lv_obj_set_width( ui_eye0, LV_SIZE_CONTENT);  /// 302
lv_obj_set_height( ui_eye0, LV_SIZE_CONTENT);   /// 301
lv_obj_set_align( ui_eye0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_eye0, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_eye0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_eye1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_eye1, &ui_img_eye1_png);
lv_obj_set_width( ui_eye1, LV_SIZE_CONTENT);  /// 302
lv_obj_set_height( ui_eye1, LV_SIZE_CONTENT);   /// 190
lv_obj_set_align( ui_eye1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_eye1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_eye1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_eye2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_eye2, &ui_img_eye2_eye2_0_png);
lv_obj_set_width( ui_eye2, LV_SIZE_CONTENT);  /// 300
lv_obj_set_height( ui_eye2, LV_SIZE_CONTENT);   /// 350
lv_obj_set_align( ui_eye2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_eye2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_eye2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_eye3 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_eye3, &ui_img_eye3_png);
lv_obj_set_width( ui_eye3, LV_SIZE_CONTENT);  /// 286
lv_obj_set_height( ui_eye3, LV_SIZE_CONTENT);   /// 270
lv_obj_set_x( ui_eye3, -10 );
lv_obj_set_y( ui_eye3, 21 );
lv_obj_set_align( ui_eye3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_eye3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_eye3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_eye0 = ui_eye0;
uic_eye1 = ui_eye1;
uic_eye2 = ui_eye2;
uic_eye3 = ui_eye3;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
uic_eye0= NULL;
ui_eye0= NULL;
uic_eye1= NULL;
ui_eye1= NULL;
uic_eye2= NULL;
ui_eye2= NULL;
uic_eye3= NULL;
ui_eye3= NULL;

}
