// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: nup_eye

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_anim_t * EyeAni0_Animation( lv_obj_t *TargetObject, int delay);
lv_anim_t * EyeAni1_Animation( lv_obj_t *TargetObject, int delay);
lv_anim_t * EyeAni2_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_eye0_[27] = {&ui_img_eye0_eye0_0_png, &ui_img_eye0_eye0_1_png, &ui_img_eye0_eye0_2_png, &ui_img_eye0_eye0_3_png, &ui_img_eye0_eye0_4_png, &ui_img_eye0_eye0_5_png, &ui_img_eye0_eye0_6_png, &ui_img_eye0_eye0_7_png, &ui_img_eye0_eye0_8_png, &ui_img_eye0_eye0_9_png, &ui_img_eye0_eye0_10_png, &ui_img_eye0_eye0_11_png, &ui_img_eye0_eye0_12_png, &ui_img_eye0_eye0_13_png, &ui_img_eye0_eye0_12_png, &ui_img_eye0_eye0_11_png, &ui_img_eye0_eye0_10_png, &ui_img_eye0_eye0_9_png, &ui_img_eye0_eye0_8_png, &ui_img_eye0_eye0_7_png, &ui_img_eye0_eye0_6_png, &ui_img_eye0_eye0_5_png, &ui_img_eye0_eye0_4_png, &ui_img_eye0_eye0_3_png, &ui_img_eye0_eye0_2_png, &ui_img_eye0_eye0_1_png, &ui_img_eye0_eye0_0_png};
const lv_img_dsc_t *ui_imgset_eye2_[12] = {&ui_img_eye2_eye2_0_png , &ui_img_eye2_eye2_1_png, &ui_img_eye2_eye2_2_png, &ui_img_eye2_eye2_3_png, &ui_img_eye2_eye2_4_png, &ui_img_eye2_eye2_5_png, &ui_img_eye2_eye2_6_png, &ui_img_eye2_eye2_7_png, &ui_img_eye2_eye2_8_png, &ui_img_eye2_eye2_9_png, &ui_img_eye2_eye2_10_png, &ui_img_eye2_eye2_11_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
lv_anim_t * EyeAni0_Animation( lv_obj_t *TargetObject, int delay)
{
lv_anim_t *out_anim;
lv_anim_del( NULL, NULL);
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_eye0_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_eye0_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame );
lv_anim_set_values(&PropertyAnimation_0, 0, 27 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 5000);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame );
out_anim = lv_anim_start(&PropertyAnimation_0);

return out_anim;
}
lv_anim_t * EyeAni1_Animation( lv_obj_t *TargetObject, int delay)
{
lv_anim_t *out_anim;
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 30, -30 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 1000);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
out_anim = lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 1000);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_1, -30, 30 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 1000 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 1000);
 lv_anim_set_repeat_count(&PropertyAnimation_1, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_1, 1000);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
out_anim = lv_anim_start(&PropertyAnimation_1);

return out_anim;
}
lv_anim_t * EyeAni2_Animation( lv_obj_t *TargetObject, int delay)
{
lv_anim_t *out_anim;
lv_anim_del( NULL, NULL);
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_eye2_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_eye2_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1300);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame );
lv_anim_set_values(&PropertyAnimation_0, 0, 12 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame );
out_anim = lv_anim_start(&PropertyAnimation_0);

return out_anim;
}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}

void ui_destroy( void )
{ui_Screen1_screen_destroy();
}
