// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: nup_eye

#ifndef _NUP_EYE_UI_H
#define _NUP_EYE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * EyeAni0_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * EyeAni1_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * EyeAni2_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_eye0_eye0_0_png);   // assets/Eye0/eye0_0.png
LV_IMG_DECLARE( ui_img_eye1_png);   // assets/eye1.png
LV_IMG_DECLARE( ui_img_eye2_eye2_0_png);   // assets/Eye2/eye2_0.png
LV_IMG_DECLARE( ui_img_eye3_png);   // assets/eye3.png
LV_IMG_DECLARE( ui_img_eye0_eye0_1_png);   // assets/Eye0/eye0_1.png
LV_IMG_DECLARE( ui_img_eye0_eye0_10_png);   // assets/Eye0/eye0_10.png
LV_IMG_DECLARE( ui_img_eye0_eye0_11_png);   // assets/Eye0/eye0_11.png
LV_IMG_DECLARE( ui_img_eye0_eye0_12_png);   // assets/Eye0/eye0_12.png
LV_IMG_DECLARE( ui_img_eye0_eye0_13_png);   // assets/Eye0/eye0_13.png
LV_IMG_DECLARE( ui_img_eye0_eye0_2_png);   // assets/Eye0/eye0_2.png
LV_IMG_DECLARE( ui_img_eye0_eye0_3_png);   // assets/Eye0/eye0_3.png
LV_IMG_DECLARE( ui_img_eye0_eye0_4_png);   // assets/Eye0/eye0_4.png
LV_IMG_DECLARE( ui_img_eye0_eye0_5_png);   // assets/Eye0/eye0_5.png
LV_IMG_DECLARE( ui_img_eye0_eye0_6_png);   // assets/Eye0/eye0_6.png
LV_IMG_DECLARE( ui_img_eye0_eye0_7_png);   // assets/Eye0/eye0_7.png
LV_IMG_DECLARE( ui_img_eye0_eye0_8_png);   // assets/Eye0/eye0_8.png
LV_IMG_DECLARE( ui_img_eye0_eye0_9_png);   // assets/Eye0/eye0_9.png
LV_IMG_DECLARE( ui_img_eye2_eye2_1_png);   // assets/Eye2/eye2_1.png
LV_IMG_DECLARE( ui_img_eye2_eye2_10_png);   // assets/Eye2/eye2_10.png
LV_IMG_DECLARE( ui_img_eye2_eye2_11_png);   // assets/Eye2/eye2_11.png
LV_IMG_DECLARE( ui_img_eye2_eye2_2_png);   // assets/Eye2/eye2_2.png
LV_IMG_DECLARE( ui_img_eye2_eye2_3_png);   // assets/Eye2/eye2_3.png
LV_IMG_DECLARE( ui_img_eye2_eye2_4_png);   // assets/Eye2/eye2_4.png
LV_IMG_DECLARE( ui_img_eye2_eye2_5_png);   // assets/Eye2/eye2_5.png
LV_IMG_DECLARE( ui_img_eye2_eye2_6_png);   // assets/Eye2/eye2_6.png
LV_IMG_DECLARE( ui_img_eye2_eye2_7_png);   // assets/Eye2/eye2_7.png
LV_IMG_DECLARE( ui_img_eye2_eye2_8_png);   // assets/Eye2/eye2_8.png
LV_IMG_DECLARE( ui_img_eye2_eye2_9_png);   // assets/Eye2/eye2_9.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
